name: TEST_CLI

on:
  push:
    branches:
      - CoverGenLite-dev
  pull_request:
    branches:
      - CoverGenLite-dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install pip==23.0
        pip install -r requirements.txt

    - name: Install models
      run: |
        python download_models.py
        wget -nc https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/model.index -O models/rvc_models/Tsoi/model.index
        wget -nc https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/model.pth -O models/rvc_models/Tsoi/model.pth

    - name: Run script
      run: |
        python src/scripts/CLI.py -i audio/test.mp3 -d Tsoi -p 0 -ir 0 -fr 3 -rms 0.25 -m "rmvpe+" -hop 32 -pro 0.33 -f "mp3"
